name: qgan_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9  # Specify a compatible Python version
  - numpy
  - pandas
  - matplotlib
  - pytorch>=1.9  # Specify PyTorch version 1.9.0 or later
  - torchvision
  - ipykernel
  - pip  # Include pip for additional installations
  - PILLOW
  - pip:
      - pennylane>=0.30  # Install PennyLane via pip
      - torchmetrics  # Added torchmetrics package